### PR TITLE
fix: support setting decodeDatesAsIso globally

### LINKED ISSUE #187: bug: dates are wrong type in Jest
Dates are typed as `string`, whereas the real type seems to be `{ value: string }`.

### PR DESCRIPTION
**Pull request by ffMathy**
Resolves https://github.com/ftrackhq/ftrack-javascript/issues/187

### CODE REVIEW

File: source/session.ts [hunk 1]
```diff
@@ -788,7 +792,10 @@ export class Session {
     logger.debug("Query", expression);
     const responses = await this.call<[QueryResponse<T>]>(
       [operation.query(expression)],
-      options,
+      {
+        decodeDatesAsIso: this.decodeDatesAsIso,
+        ...(options || {})
+      },
```
Comment (jimmycallin) [inline source/session.ts:798]: Please move this to the `call` function to set it for mutation calls as well.

**Comment by jimmycallin** [comment]
Oh, we missed adding this in the constructor? Our bad – thanks for the patch!

Please move the option to the call function, and we can merge this.

**Review by jimmycallin — CHANGES_REQUESTED** [review]

File: source/session.ts [hunk 2]
```diff
@@ -624,7 +628,7 @@ export class Session {
         throw this.getErrorFromResponse(response);
       }
       try {
-        return this.decode(response, {}, decodeDatesAsIso);
+        return this.decode(response, {}, decodeDatesAsIso || this.decodeDatesAsIso);
```
Comment (gismya) [inline source/session.ts:631]: This would force `decodeDatesAsIso` to true if it were set to true globally, we want the global value to be overridden by the local value if there is one.

**Review by gismya — CHANGES_REQUESTED** [review]

File: source/session.ts (hunk 2 above)
Comment (ffMathy) [reply source/session.ts:631]: Oh, right... What was I thinking 🤣 I'll fix it Monday (since I am on a factory tour tomorrow), but feel free to swap them and merge before then.

File: source/session.ts [hunk 3]
```diff
@@ -624,7 +628,7 @@ export class Session {
         throw this.getErrorFromResponse(response);
       }
       try {
-        return this.decode(response, {}, decodeDatesAsIso);
+        return this.decode(response, {}, this.decodeDatesAsIso || decodeDatesAsIso);
```
Comment (gismya) [inline source/session.ts:631]: This doesn't allow you to override a `true` default for decodeDatesAsIso.

**Review by gismya — CHANGES_REQUESTED** [review]

File: source/session.ts (hunk 3 above)
Comment (ffMathy) [reply source/session.ts:631]: Ahhhh I see! Will correct.

Comment (ffMathy) [reply source/session.ts]: There we go!

**Review by gismya — CHANGES_REQUESTED** [review]
`decodeDatesAsIso` is defaulted to false in call, so that won't work either. Probably best to default all the different `decodeDatesAsIso` ( in `decode()` and `call()`)  to `this.decodeDatesAsISO`, instead of making other changes inside `call()`.

Also, would be great if you could add tests for this as well, but not strictly necessary.

**Comment by ffMathy** [comment]
> `decodeDatesAsIso` is defaulted to false in call, so that won't work either. Probably best to default all the different `decodeDatesAsIso` ( in `decode()` and `call()`) to `this.decodeDatesAsISO`, instead of making other changes inside `call()`.

I tried doing this now. Let me know if I understood what you meant correctly. If not, I think I need some assistance perhaps?

File: source/session.ts [hunk 4]
```diff
@@ -578,14 +582,18 @@ export class Session {
...
   ): Promise<IsTuple<T> extends true ? T : T[]> {
     if (this.initializing) {
       await this.initializing;
     }
     const url = `${this.serverUrl}${this.apiEndpoint}`;
 
+    decodeDatesAsIso = decodeDatesAsIso === undefined ?
+      this.decodeDatesAsIso :
+      decodeDatesAsIso;
+
```
Comment (gismya) [inline source/session.ts:596]:
```suggestion
      decodeDatesAsIso = this.decodeDatesAsIso,
    }: CallOptions = {},
  ): Promise<IsTuple<T> extends true ? T : T[]> {
    if (this.initializing) {
      await this.initializing;
    }
    const url = `${this.serverUrl}${this.apiEndpoint}`;
```

I haven't tested it, but this way should work, unless I'm totally mistaken. You can also set the default to `this.decodeDatesAsIso` in the decode method as well.

**Review by gismya — APPROVED** [review]
Added tests, fixed a type error, and prettier formatting. 

Thank you @ffMathy!

**Review by jimmycallin — APPROVED** [review]

**Comment by ffMathy** [comment]
Thanks for the assist! ❤️ 

And sorry for maybe not being too thorough around testing. Things are busy these days, so I must admit I've been trying to limit my investment in this.

**Comment by gismya** [comment]
No worries at all. Appreciate any contributions.
